CREATE TABLE TEACHERS_AUD
(
    EVENT_ID        int auto_increment
        primary key,
    EVENT_DATE      datetime     not null,
    EVENT_TYPE      varchar(255) null,
    TEACHER_ID      INT,
    OLD_FIRSTNAME   varchar(255) null,
    NEW_FIRSTNAME   varchar(255) null,
    OLD_LASTNAME    varchar(255) null,
    NEW_LASTNAME    varchar(255) null,
    OLD_DESCRIPTION varchar(255) null,
    NEW_DESCRIPTION varchar(255) null
);


CREATE DEFINER = kasia@LOCALHOST TRIGGER TEACHERS_DELETE
    AFTER DELETE
    ON TEACHERS
    FOR EACH ROW
BEGIN
    INSERT INTO TEACHERS_AUD (EVENT_DATE, EVENT_TYPE, TEACHER_ID, OLD_DESCRIPTION, OLD_FIRSTNAME, OLD_LASTNAME)
        VALUE (CURTIME(), 'DELETE', OLD.ID, OLD.DESCRIPTION, OLD.FIRSTNAME, OLD.LASTNAME);
END;

CREATE DEFINER = kasia@LOCALHOST TRIGGER TEACHERS_CREATE
    AFTER INSERT
    ON TEACHERS
    FOR EACH ROW
BEGIN
    INSERT INTO TEACHERS_AUD (EVENT_DATE, EVENT_TYPE, TEACHER_ID, NEW_DESCRIPTION, NEW_FIRSTNAME, NEW_LASTNAME)
        VALUE (CURRENT_TIME, 'INSERT', NEW.ID, NEW.DESCRIPTION, NEW.FIRSTNAME, NEW.LASTNAME);
END;

CREATE DEFINER = kasia@LOCALHOST TRIGGER TEACHERS_UPDATE
    AFTER UPDATE
    ON TEACHERS
    FOR EACH ROW
BEGIN
    INSERT INTO TEACHERS_AUD(EVENT_DATE, EVENT_TYPE, TEACHER_ID, NEW_DESCRIPTION, NEW_FIRSTNAME, NEW_LASTNAME,
                             OLD_DESCRIPTION, OLD_FIRSTNAME, OLD_LASTNAME)
    VALUES (CURTIME(), 'UPDATE', OLD.ID, NEW.DESCRIPTION, NEW.FIRSTNAME, NEW.LASTNAME, OLD.DESCRIPTION,
            OLD.FIRSTNAME, OLD.LASTNAME);
END;


